"x/claim":
  - x/claim/**/*
"x/farming":
  - x/farming/**/*
"x/liquidity":
  - x/liquidity/**/*
"x/liquidstaking":
  - x/liquidstaking/**/*
"x/mint":
  - x/mint/**/*
"x/marketmaker":
  - x/marketmaker/**/*
"documentation":
  - docs/**/*
"build":
  - Makefile
  - scripts/*
"ci":
  - buf.yaml
  - .golangci.yml